# SnapRAID configuration file

# Parity location(s)
1-parity /storage/parity1/snapraid.parity
# 2-parity /mnt/parity2/snapraid.parity

# Content file location(s)
content /var/snapraid.content
content /storage/disk1/.snapraid.content
content /storage/disk2/.snapraid.content

# Data disks
data d1 /storage/disk1
data d2 /storage/disk2

# Excludes hidden files and directories
exclude *.!sync
exclude *.unrecoverable
exclude ._.DS_Store
exclude ._AppleDouble
exclude .AppleDB
exclude .AppleDouble
exclude .DS_Store
exclude .fseventsd
exclude .nfo
exclude .Spotlight-V100
exclude .TemporaryItems
exclude .Thumbs.db
exclude .Trashes
exclude /lost+found/
exclude /tmp/
exclude appdata/

