# version: '3'
services:


  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    # Not Needed with NPM
    # ports:
    #   - "${PORT:-8191}:8191"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.$TRAEFIK_PRIVATE_DOMAIN`)"
      - "traefik.http.routers.flaresolverr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr.tls=true"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"

    restart: no

# Use the IPv6 network for containers that need IPv6 Internet Access
networks:
  default:
    name: "$DOCKER_NETWORK_NAME"
    external: true
